name: evening_gown_ideas
description: A new Flutter project.

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=2.18.1 <3.0.0'

dependencies:
  flutter:
    sdk: flutter


  http: ^0.13.5
  cupertino_icons: ^1.0.2
  material_dialogs: ^1.1.3
  device_info_plus: ^5.0.5
  flutter_sms_inbox: ^1.0.1
  permission_handler: ^10.1.0
  shared_preferences: ^2.0.15
  cached_network_image: ^3.2.2
  flutter_background_service: ^2.4.3
  flutter_local_notifications: ^12.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0

flutter:

  uses-material-design: true

  assets:
    - assets/

